# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- dev-ng

schedules:
  - cron: "0 9 1 * *"
    displayName: Monthly build
    branches:
      include:
        - dev-ng
    always: true

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'WebSocket4Net.build'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:BuildAndPack'

- task: CopyFiles@2
  inputs:
    contents: '**\HiraokaHyperTools.WebSocket4Net.*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
